language: python

python: 
    - "2.7"

services: mysql

install:
	- pip install -r requirements.txt

before_script:
	- mysql -e 'create database CRYPTOFOLIO;'
	- python manage.py migrate --noinput
	- python manage.py collectstatic

script:
	- python manage.py test
